on: pull_request_target
name: Changelog Reminder
jobs:
  remind:
    name: Changelog Reminder
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Changelog Reminder
      uses: peterjgrainger/action-changelog-reminder@v1.2.0
      with:
        changelog_regex: '/CHANGELOG.md'
        customPrMessage: 'You are welcome to add an entry to the CHANGELOG.md as well'
      env:
        GITHUB_TOKEN: ${{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 }}
